apiVersion: v1
kind: Pod
metadata:
  name: my-docker
  labels:
    app: my-docker
spec:
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket 
  containers:
    - name: my-docker
      image: docker
      command: ["sleep"]
      args: ["100000"]
      volumeMounts:
        # if we see containers inside this, it will list out host ones
        # like Kubernetes one since its talking to host path docker.sock
        - mountPath: /var/run/docker.sock  
          name: docker-socket
    
  