apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      # If container fails readiness probe, no traffic will be assigned to this pod 
      # Check events in kubectl describe pod <pod-name> 
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        failureThreshold: 1
        initialDelaySeconds: 2
        periodSeconds: 5
        