apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume
spec:
  accessModes: 
    - "ReadWriteOnce"
  capacity:
    storage: 10Mi
  storageClassName: my-storage-class
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /my-pv-vol
  nodeAffinity: # Defines constraints which nodes this volume can be accessed from
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
