apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-persistent-volume-claim
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: my-storage-class
  resources:
    requests:
      storage: 10Mi