apiVersion: v1
kind: Pod
metadata:
  name: external-webapp
  labels:
    app: external-webapp
spec:
  containers:
    - name: external-webapp
      image: deepagarwal/simple-py-webapp
      ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  selector:
    app: external-webapp
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 80