apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    app: my-nginx # must match label of the pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000