apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      name: py-app
      labels:
        app: py-app
    spec:
      containers:
        - name: py-app-v2-container
          image: deepicertis/app:v2
          ports:
            - containerPort: 80