apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  replicas: 4
  minReadySeconds: 1 # Default 0
  progressDeadlineSeconds: 60 # Default 600s
  revisionHistoryLimit: 5 # Default 10
  strategy:
    type: RollingUpdate # Default
    rollingUpdate:
      maxSurge: 1 # Default 25%
      maxUnavailable: 1 # Default 25%
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      name: py-app
      labels:
        app: py-app
    spec:
      containers:
        - name: py-app-v2-container
          image: deepicertis/app:v2
          ports:
            - containerPort: 80