apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: web-ctr
      image: nigelpoulton/nginxadapter:1.0
      ports:
        - containerPort: 80
      # Transforms the metrics from above app into acceptable format by Prometheus 
    - name: transformer
      image: nginx/nginx-prometheus-exporter
      args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
      ports:
        - containerPort: 9113