apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "my-storage-class"
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  containers:
   - name: my-nginx-container
     image: alpine
     ports:
       - containerPort: 80
     volumeMounts:
       - mountPath: /usr/share/ngin
         name: my-html-vol
  volumes:
    - name: my-html-vol
      persistentVolumeClaim:
        claimName: my-pvc