apiVersion: v1
kind: Pod
metadata:
  name: app-settings-env-file
spec:
  containers:
    - name: app-settings-env-file
      image: deepagarwal/config-map-app
      ports:
        - containerPort: 80
      # envFrom gets all the environment variables in one go
      envFrom:
        - configMapRef:
            # Run this before "kubectl create configmap settings-env-file --from-env-file=settings.env"
            name: settings-env-file