apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
# Once run, get into the shell and curl to http://ambassador-service:8080. 
# You should get output of external web app 